#!/usr/bin/env python
# vi: set ft=python
"""
This script will set up all the files in the correct places.

Using --force will remove any previous files
"""

import os, sys
import getopt

force = False

class Usage(Exception):
    def __init__(self, msg):
        self.msg = msg

def create_link(link_name, source_name, verbose=False):
    if verbose:
        print "about to link %s to %s" % (link_name, source_name)
    if not os.path.isfile(link_name):
        if verbose:
            print "No file found so just created link"
        os.symlink(source_name, link_name)
    else:
        if not os.path.islink(link_name):
            if verbose:
                print "File found so move it and create link"
            os.rename(link_name, link_name+'.orig')
            os.symlink(source_name, link_name)
        elif os.readlink(link_name) != source_name:
            if verbose:
                print "Bad link found so remove it and recreate link"
            os.remove(link_name)
            os.symlink(source_name, link_name)
        else:
            if verbose:
                print "Link already present"

def setup_dotlink(filename, verbose=False):
    link_name = os.path.join(os.environ["HOME"], '.' + filename)
    source_name = os.path.join(os.environ["HOME"], 'dev', 'dotfiles', filename)
    create_link(link_name, source_name, verbose)

def setup_terminator_config(verbose=False):
    link_name = os.path.join(os.environ["HOME"], '.config', 'terminator', 'config')
    source_name = os.path.join(os.environ["HOME"], 'dev', 'dotfiles', 'terminator.config')
    create_link(link_name, source_name, verbose)

def setup_janus(verbose=False):
    # run the bootstrap script
    pass

def main(argv=None):
    verbose = False
    if argv is None:
        argv = sys.argv
    try:
        try:
            opts, args = getopt.getopt(argv[1:], "fhv", ["force", "help",
                    "verbose"])
        except getopt.error, msg:
             raise Usage(msg)
        # more code, unchanged
        for o, a in opts:
            if o in ["-v", "--verbose"]:
                verbose = True
        # set up the rc file links
        for file in ["ackrc", "bashrc", "gvimrc.local", "inputrc", "janus.rake",
                    "tmux.conf", "vimrc.local"]:
            setup_dotlink(file, verbose)
        setup_terminator_config(verbose)
        setup_janus(verbose)
    except Usage, err:
        print >>sys.stderr, err.msg
        print >>sys.stderr, "for help use --help"
        return 2

if __name__ == "__main__":
    sys.exit(main())
