#!/usr/bin/env python
# from https://bloerg.net/2013/10/09/syncing-mails-with-mbsync-instead-of-offlineimap.html

import argparse
import getpass
import keyring
import sys

SERVICE = 'mbsync'


def get_pass(user):
    return keyring.get_password(SERVICE, user)


def main():

    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--set', '-s', type=str, help='Account to save password')
    group.add_argument('--get', '-g', type=str, help='Account to get password')

    args = parser.parse_args()

    if args.set:
        password = getpass.getpass()
        keyring.set_password(SERVICE, args.set, password)
    else:
        print(get_pass(args.get))
    return 0

if __name__ == '__main__':
    sys.exit(main())

# vi: ft=python
