typeset -U path
# from http://superuser.com/a/39995/1630
# if the directory exists, and the directory is not already
# on the path, then add to $PATH
function pathadd {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        path=($path $1)
    fi
}

typeset -T LD_LIBRARY_PATH ld_library_path
typeset -U ld_library_path
function ldlibrarypathadd {
    if [ -d "$1" ] && [[ ":$LD_LIBRARY_PATH:" != *":$1:"* ]]; then
        ld_library_path=($ld_library_path $1)
    fi
}

pathadd $HOME/.wp-cli/bin
pathadd $HOME/Dropbox/tech/bin
pathadd $HOME/lib/pebble/bin
pathadd /var/lib/gems/1.8/bin
pathadd /var/lib/gems/1.9.1/bin
pathadd $HOME/node_modules/phantomjs/bin
pathadd $HOME/.local/bin
pathadd $HOME/.local/share/go/bin
pathadd $HOME/.linuxbrew/bin
pathadd $HOME/bin

ldlibrarypathadd /usr/local/lib
ldlibrarypathadd $HOME/.linuxbrew/lib


if [[ -o login ]]; then
    # disable Ctrl-S / Ctrl-Q
    stty -ixon
    #stty stop '' -ixon -ixoff
fi
